(defun fizzbuzz (mulA mulB max)
	(setq max (- max 1))
	(setq mulC (* mulA mulB))
	(setq a (floor max mulA))
	(setq b (floor max mulB))
	(setq c (floor max mulC))
	(-(+ (* mulA (floor (* a (+ a 1)) 2))
		(* mulB (floor (* b (+ b 1)) 2)))
		(* mulC (floor (* c (+ c 1)) 2))))