(defparameter *max* 4000000)
(defparameter *n1* 1)
(defparameter *n2* 1)
(defparameter *num* 1)
(defparameter *total* 0)

(loop while (<= *num* *max*) 
  do (setq *num* (+ *n1* *n2*)) 
	do (setq *n1* *n2*) 
  do (setq *n2* *num*) 
  do (if (= 0 (mod *num* 2)) 
	  	(setq *total* (+ *total* *num*)))
)

(print *total*)